root = "."
testdata_dir = "testdata"
tmp_dir = "dev/air/account_tmp"

[build]
  args_bin = []
  bin = "./dev/air/account_tmp/main"
  cmd = "go build -o ./dev/air/account_tmp/main cmd/account/main.go"
  delay = 1000
  exclude_dir = ["account_tmp", "vendor", "testdata", "proto"]
  exclude_file = ["go.mod", "go.sum", "Makefile", "README.md", ".gitignore", ".env"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd/account", "internal/account", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
